FROM golang:1.7-alpine

COPY glide.yaml /go/src/github.com/microservices-demo/user/glide.yaml
COPY glide.lock /go/src/github.com/microservices-demo/user/glide.yaml
WORKDIR /go/src/github.com/microservices-demo/user/

RUN apk update
RUN apk add git
RUN go get -v github.com/Masterminds/glide 
RUN glide install

RUN apk add --update gcc musl-dev

COPY . /go/src/github.com/microservices-demo/user/

#RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o /user main.go
#RUN CGO_ENABLED=1 go build -a -installsuffix cgo -o /user main.go
RUN CGO_ENABLED=0 go build -a -linkshared -installsuffix cgo -o /user main.go

FROM alpine:3.4

RUN apk add --update gcc musl-dev linux-headers
COPY rbinder.c rbinder.c
COPY uthash.h uthash.h
RUN gcc -fPIC -shared -o rbinder.so rbinder.c -ldl

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

RUN	addgroup -g ${SERVICE_GID} ${SERVICE_GROUP} && \
	adduser -g "${SERVICE_NAME} user" -D -H -G ${SERVICE_GROUP} -s /sbin/nologin -u ${SERVICE_UID} ${SERVICE_USER} && \
	apk add --update libcap

ENV HATEAOS user:8080
ENV USER_DATABASE mongodb
ENV MONGO_HOST user-db

WORKDIR /
EXPOSE 8080
COPY --from=0 /user /

RUN	chmod +x /user && \
	chown -R ${SERVICE_USER}:${SERVICE_GROUP} /user && \
	setcap 'cap_net_bind_service=+ep' /user

#USER ${SERVICE_USER}

ENV LD_PRELOAD /rbinder.so
CMD ["/user", "-port=8080"]
#CMD ["/user", "-port=80"]
